//  Sum of bit differences(gfg)

class Solution{
public:
	long long sumBitDifferences(int arr[], int n) {
	    long long ans = 0; // Initialize result

	    // traverse over all bits
	    for (int i = 0; i < 32; i++) {
	        // count number of elements with i'th bit set
	        int count = 0;
	        for (int j = 0; j < n; j++)
	            if ((arr[j] & (1 << i)))
	                count++;

	        // Add "count * (n - count) * 2" to the answer
	        ans += ((long long) count * (long long) (n - count) * 2LL);
	    }

	    return ans;
	}
};
