//   Count pairs Sum in matrices (GFG)


class Solution{
public:	
	
	int countPairs(vector<vector<int>> &mat1, vector<vector<int>> &mat2, int n, int x)
	{
	     set<int>st ;
    
    for( int i = 0 ; i<n ; i++)
    {
        
        for( int j = 0 ; j<n ; j++)
        {
        st.insert(mat2[i][j]) ;
    }
    
    }
    
    int count = 0 ;
    
    
    for( int i = 0 ; i<n ; i++)
    {
        
        for( int j = 0 ; j<n ; j++)
        {
        
        int d = x-mat1[i][j] ;
        if( st.find(d) != st.end())
        {
            count++ ;
        }
    }
    
    }
    
    return count ;
	    // Your code goes here
	}
};
